baseURL = 'https://helloword1289.github.io/'
languageCode = 'zh-cn'
title = '我的技术博客'
theme = 'PaperMod'

[taxonomies]
tag = "tags"
category = "categories"

[params]
defaultTheme = "auto"
ShowShareButtons = true
ShowReadingTime = true
ShowCodeCopyButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowToc = true
comments = false

[params.profileMode]
enabled = true
title = "欢迎来到我的博客"
subtitle = "分享技术，记录成长"
imageUrl = ""
imageTitle = "My Image"

[[params.socialIcons]]
name = "github"
url = "https://github.com/helloword1289"

[menu]
[[menu.main]]
identifier = "home"
name = "首页"
url = "/"
weight = 10

[[menu.main]]
identifier = "posts"
name = "文章"
url = "/posts/"
weight = 20

[[menu.main]]
identifier = "tags"
name = "标签"
url = "/tags/"
weight = 30

[[menu.main]]
identifier = "archives"
name = "归档"
url = "/archives/"
weight = 40
